variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_1_az1_cidr" {}
variable "public_subnet_2_az2_cidr" {}
variable "public_subnet_3_az2_cidr" {}
variable "private_subnet_1_az1_cidr" {}
variable "private_subnet_2_az2_cidr" {}
variable "private_subnet_3_az2_cidr" {}